[GLOBAL]
pants_version = "2.17.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages.add = [
  "pants.backend.python",
   "byo_linters",
# Convenient to use instead while developing/debuggin the plugin:
#  "pants.backend.byolinter",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true

[python.resolves]
byo_flake8 = "byo_flake8.lock"
byo_black = "byo_black.lock"

[source]
root_patterns = ["/"]
