[GLOBAL]
pants_version = "2.17.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.flake8",
  "byo_linters",
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_constraints = ["==3.9.*"]

[source]
root_patterns = ["/"]
